### ISSUE TITLE
Problem with identyfing the number of tests run

### ISSUE THREAD

**Issue by JJ** [Wiiseguy/aqa#4]
As you can see in #3 , the "pass 20" line is not recognized by `aqa`, which says `Ran -1 tests succesfully! (108ms)`. It's possible that the regex used to recognize that line will have to be expanded somehow. Anyway, these are ancient tests, so you might want to simply skip them.

**Comment by Wiiseguy** [comment]
The -1 was caused by there being no parseable output. I've cloned your repo and noticed that the scripts aqa is running did not contain a require('aqa') anywhere, which was the cause. 
I've made it so that is no longer necessary.
I've also added a --tap flag, so aqa no longer adds its own reporting as that might upset whatever is used to parse the TAP result.
This mean's you'll have to run your script as such: `aqa tests/test-*.js --tap` for the best results.

Like with #3  - this issue should be solved with 1.2.11

**Comment by JJ** [comment]
That's awesome, thanks!

**Comment by Wiiseguy** [comment]
Please let me know if this resolved this issue and #3

**Comment by Wiiseguy** [comment]
@JJ is the thumbs up a yes? 😀

**Comment by JJ** [comment]
It's rather an ack... I still need to check.
